services:
  # ---- optional infra you may want later ----
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    ports: [ "5432:5432" ]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes: [ "miniodata:/data" ]
    ports: [ "9000:9000", "9001:9001" ]

  # ---- the only piece we actually run right now ----
  ingest:
    build: ../ingest          # path to Dockerfile
    command: ["python", "main.py"]
    environment:
      HEARTBEAT_INTERVAL: 5   # seconds
      CIK: "0000320193"              # Apple—for tests
      POLL_INTERVAL: "600"           # seconds
      USER_AGENT: "me@example.com FinDocAgent/0.1" #your user
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "admin123"
      MINIO_BUCKET: "filings"
      SEC_API_KEY: "16328f06c7b6174f08ebb7d902287d6382fd6d247a21d43d50f82cfd5435d964"
    depends_on:
      - postgres
      - minio                 # comment these if you removed the blocks

volumes:
  pgdata:
  miniodata:
